# Generated by Django 2.2.6 on 2019-11-10 06:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0002_user'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userprofile',
            name='profile_pic',
            field=models.ImageField(blank=True, default='profile_pics/default_pic.png', upload_to='profile_pics/'),
        ),
    ]
