# Generated by Django 2.2.1 on 2019-11-07 07:00

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='item',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('item_name', models.CharField(max_length=128)),
                ('item_image', models.ImageField(null=True, upload_to='item_image/')),
                ('item_description', models.CharField(max_length=256)),
                ('item_date', models.DateField()),
                ('item_status', models.CharField(choices=[('L', 'LOST'), ('F', 'FOUND')], max_length=1)),
                ('item_user', models.CharField(max_length=128)),
                ('item_last_place_seen', models.CharField(max_length=256)),
            ],
        ),
    ]
