# Generated by Django 2.2.6 on 2019-11-09 19:27

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('item', '0002_item_user'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='item',
            name='item_user',
        ),
    ]
