# Generated by Django 2.2.1 on 2019-11-26 04:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('item', '0005_auto_20191125_1439'),
    ]

    operations = [
        migrations.AlterField(
            model_name='item',
            name='item_image',
            field=models.ImageField(blank=True, null=True, upload_to='item_image/'),
        ),
    ]
