# Generated by Django 2.2.1 on 2019-11-26 04:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('item', '0006_auto_20191126_1013'),
    ]

    operations = [
        migrations.AlterField(
            model_name='item',
            name='item_image',
            field=models.ImageField(blank=True, default='/media/item_image/default.png', null=True, upload_to='item_image/'),
        ),
    ]
